import { DatabaseSync } from 'node:sqlite';
import fs from 'fs';
import { spawn } from 'child_process';
import assert from 'assert';

console.log('==========================================================================');
console.log('Ebb Verification Test Suite: Part 1 Phase 1');
console.log('==========================================================================\n');

// 1. Verify that database file exists (will be generated by server)
const DB_PATH = 'ebb.db';
if (fs.existsSync(DB_PATH)) {
    console.log('✔ Verification 1: Local SQLite database file found (ebb.db)');
} else {
    console.log('Database file not initialized yet. Launching server first...');
}

// 2. Start the local server in the background
console.log('Launching backend server...');
const serverProcess = spawn('node', ['server.mjs'], { stdio: 'inherit' });

// Give server 1.5 seconds to spin up and bind port 3000
await new Promise(resolve => setTimeout(resolve, 1500));

try {
    // 3. Test Database GCM Encryption at Rest (Verify SQLCipher Check)
    console.log('\nChecking Database Encryption at Rest...');
    const localDb = new DatabaseSync(DB_PATH);
    const userRow = localDb.prepare('SELECT oauth_google_cal FROM user_profiles LIMIT 1').get();
    
    assert(userRow !== undefined, 'User profiles table should have seeded Anya');
    console.log('✔ Raw encrypted field content fetched:', userRow.oauth_google_cal);
    
    const parsedObj = JSON.parse(userRow.oauth_google_cal);
    assert(parsedObj.iv !== undefined && parsedObj.tag !== undefined && parsedObj.content !== undefined, 
        'Database fields must contain IV and authentication Tag parameters');
    console.log('✔ Verification 2: Database encryption verified at rest (GCM IV & Tag present).');

    // 4. Test Ingestion API (Successful parse)
    console.log('\nTesting Ingestion API (High-Confidence Voice Log)...');
    const ingestSuccessRes = await fetch('http://localhost:3000/api/v1/somatic/ingest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            audio_checkin_transcript: 'Woke up feeling recovered, HRV looks stable today.',
            wearable_sleep_seconds: 29520, // 8.2 hrs
            wearable_hrv_ms: 78,
            subjective_alertness: 5
        })
    });
    
    const ingestSuccessData = await ingestSuccessRes.json();
    console.log('Ingest Response:', ingestSuccessData);
    assert.strictEqual(ingestSuccessData.status, 'INGEST_SUCCESS');
    assert(ingestSuccessData.confidence_score >= 0.75, 'Confidence score must exceed quality gate');
    console.log('✔ Verification 3: Successful high-confidence voice check-in written silently to SQLite.');

    // 5. Test Ingestion API (Low-Confidence Gate Fail Check)
    console.log('\nTesting Ingestion API (Low-Confidence Muddled Voice Log)...');
    const ingestFailRes = await fetch('http://localhost:3000/api/v1/somatic/ingest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            audio_checkin_transcript: 'Mumble blur noise, feeling sleepy during workout...',
            wearable_sleep_seconds: 20880, // 5.8 hrs
            wearable_hrv_ms: 24,
            subjective_alertness: 2
        })
    });
    
    const ingestFailData = await ingestFailRes.json();
    console.log('Ingest Fail Response:', ingestFailData);
    assert.strictEqual(ingestFailData.status, 'CONFIDENCE_GATE_FAIL');
    assert(ingestFailData.confidence_score < 0.75, 'Confidence must fall below 0.75 trigger');
    assert(ingestFailData.payload_pending !== undefined, 'Must return the payload in a pending state');
    console.log('✔ Verification 4: Confidence Scoring Gate successfully blocked low-confidence SQLite write.');

    // 6. Test Calendar Proposal generation
    console.log('\nTesting Calendar Shield Proposal Generation...');
    // We first trigger Oura sync to populate low biometrics (HRV 24ms)
    await fetch('http://localhost:3000/api/v1/oauth/oura/sync', { method: 'POST' });
    
    const proposalRes = await fetch('http://localhost:3000/api/v1/calendar/shield-proposal', { method: 'POST' });
    const proposalData = await proposalRes.json();
    console.log('Shield Proposal:', proposalData);
    assert.strictEqual(proposalData.somatic_battery, 45);
    assert(proposalData.proposed_actions.length > 0, 'Must generate proposals on low readiness');
    console.log('✔ Verification 5: Somatic Calendar Rescheduler correctly generated calendar shifts and buffers.');

    // 7. Test Mid-Day Rebuild (Reset of the day)
    console.log('\nTesting Mid-Day Reset Rebuild API...');
    const rebuildRes = await fetch('http://localhost:3000/api/v1/calendar/rebuild', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            current_time: new Date().toISOString(),
            triggered_by: 'REAL_TIME_HRV_DIP',
            somatic_battery_current: 20
        })
    });
    const rebuildData = await rebuildRes.json();
    console.log('Rebuild Action Response:', rebuildData);
    assert.strictEqual(rebuildData.rebuild_executed, true);
    console.log('✔ Verification 6: Mid-day reset recalculation completed successfully.');

    // 8. Test Dashboard payload decryption
    console.log('\nTesting Dashboard Decryption Verification...');
    const dashboardRes = await fetch('http://localhost:3000/api/v1/somatic/dashboard');
    const dashboardData = await dashboardRes.json();
    console.log('Dashboard dimensions loaded:', dashboardData.dimensions.map(d => d.dimension_name));
    
    const aestheticDim = dashboardData.dimensions.find(d => d.dimension_name === 'SOMATIC_AESTHETIC');
    const nutritionDim = dashboardData.dimensions.find(d => d.dimension_name === 'NUTRITION');
    
    assert(aestheticDim !== undefined, 'Aesthetic ledger should be written');
    assert(nutritionDim !== undefined, 'Nutrition ledger should be written');
    
    // Assert that micronutrients (Zinc/Iron/Selenium) were decrypted successfully
    assert.strictEqual(nutritionDim.payload.nutrients.zinc_mg, 15, 'Zinc macro must be decrypted');
    assert.strictEqual(nutritionDim.payload.nutrients.iron_mg, 12, 'Iron macro must be decrypted');
    console.log('✔ Decrypted Nutrition payload details:', nutritionDim.payload);
    console.log('✔ Verification 7: Decryption layer verified. Encrypted payload json read back successfully.');

    console.log('\n==========================================================================');
    console.log('✔ ALL TEST CASES COMPLETED SUCCESSFULLY! Phase 1 is fully functional!');
    console.log('==========================================================================');

} catch (error) {
    console.error('\n✖ TEST SUITE FAILED with error:');
    console.error(error);
} finally {
    // Terminate server process
    console.log('\nShutting down server...');
    serverProcess.kill('SIGINT');
}
